spring:
  application:
    name: parking-service
  datasource:
    url: jdbc:h2:mem:parkingdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8085